### ISSUE TITLE
Pesquisa e orçamento prévio de carros plataforma viáveis para o projeto

### ISSUE THREAD

**Issue by markosmcosta** [PI2-Irri/docs#12]
**Descrição**

Enquanto não forem estabelecidas as dimensões do reservatório de água e das placas solares (área de Energia), bem como escolhida a motobomba, é necessário realizar uma pesquisa e um orçamento prévio de carros-plataforma possíveis para aplicação no sistema.

**Tarefa**

- [x] Realizar a pesquisa e verificar quais são os modelos mais viáveis em termos da aplicação final e de custo.

**Critérios de aceitação**

- [x] Documentação no prazo de 8/09 a 14/09.

**Comment by markosmcosta** [comment]
Foi necessário alterar o projeto inicial do carro plataforma em virtude das dimensões da placa solar que será instalada no mesmo, bem como sua disposição sobre a plataforma concebida. Serão necessárias adaptações na plataforma para conter todos os componentes eletrônicos ligados à motobomba e ao reservatório de água.

**Comment by dhiemerson** [comment]
O orçamento prévio foi realizado e será utilizado uma plataforma de 200kg com dimensões de 100x60cm no valor de 424,90.
