### ISSUE TITLE
Escolha da bomba hidráulica

### ISSUE THREAD

**Issue by thmiranda** [PI2-Irri/docs#15]
Com base nos cálculos de perda de carga e simulação no software EPANET 2.0 iremos escolher nossa bomba.

- [x] Cálculo Manual
- [x] Revisão

**Comment by thmiranda** [comment]
- [x] Cálculo Manual 
- [x] Revisão do Cálculo

**Comment by thmiranda** [comment]
- [ ] Simulação 
- [ ] Revisão da Simulação

**Comment by thmiranda** [comment]
Esta tarefa depende da Issue do Cálculo da Perda de Carga Hidráulica, com esta concluída, devemos avaliar se a bomba irá cavitar (Avaliar o NPSH)

**Comment by thmiranda** [comment]
Simulação da bomba em software esta fora de cogitação por falta de tempo.

**Comment by thmiranda** [comment]
Avaliação da Curva de Canalização da _Issue de Perda Carga Hidráulica_ com a eficiência da bomba. Essas curvas devem se encontrar, se isso não acontecer, devemos buscar 90% do ponto ótimo de operação.

**Comment by thmiranda** [comment]
Foi decidido utilizar bomba hidráulica AC, com base na curva de perda de carga calculada com tabela em Excel. 

Os seguintes modelos de aspersores estão aptos para o projeto

1. http://www.vonder.com.br/produto/irrigador_setorial_tipo_espiga_vonder/5210
2. https://www.biosementes.com.br/loja/item/Aspersor-para-Irrigacao-JET8022-510-L%7B47%7Dh-Rosca-1%7B47%7D2"-diametro-22-m.html
2.1 https://www.biosementes.com.br/loja/item/Haste-com-rosca-interna-1%7B47%7D2-com-conector-para-engate-rapido.html

**Comment by rafamarques56** [comment]
2.2 - https://www.biosementes.com.br/loja/item/Aspersor-Setorial-para-irrigacao-JET-8427-bocal-3%7B47%7D4-pol-%252d-pastagem%2C-jardim%2C-outros.html

**Comment by thmiranda** [comment]
As bombas em processo de escolha são:

Anauger Vibratória 450 Watts
Bomba Dágua   Submersa 3.4 Pol. 680-S HB Bombas
Bomba Submersa (Sapo) 9.0 450w   Bluma - 220v
Bomba Submersa Vibratória P/   Poço Tipo Sapo Rymer 1500 220v
Bomba   Centrífuga Monoestágio Schneider BCR-2010 1cv 220V
Bomba   Centrífuga Schneider BC-92 T 1A 1cv 127/220V Monofásico C/Intermediário
Bomba Centrífuga Monoestágio   Schneider BC-92S 1C 1cv 127/220V Monofásico
Bomba 1/2cv Lepono
Motobomba Periférica 1cv   Apm75 Lepono

Avaliando a vazão que necessitamos e custos do projeto, as bombas LEPONO e SCHNEIDER BCR 2010, qualquer uma destas podem ser compradas.

**Comment by thmiranda** [comment]
Bomba definida, previsão de compra para o dia 18/10.
