### ISSUE TITLE
Sistema de Atuadores - Refatorar Requisitos/Especificar do Sensoriamento 

### ISSUE THREAD

**Issue by mendes-davi** [PI2-Irri/docs#18]
**Descrição**

Tópico voltado para as atividades de especificação do sensoriamento do Sistema de Atuadores. Requer que os requisitos iniciais sejam refatorados para incluir sensoriamento do sistema off-grid e adequações ao sistema de bombeamento.

**Tarefas**

- [x] Refatorar Requisitos do Sensoriamento do Sistema de Atuadores @mendes-davi 
- [x] Especificar Sensoriamento do Gasto Hídrico @josuebonfim 
- [x] Especificar Sensoriamento do Sistema Offgrid @mendes-davi
- [x] Especificar Sensoriamento do Reservatório (nível de água) @josuebonfim 
- [ ] Especificação do módulo de Relês @josuebonfim 

**Critérios de Aceitação**
- [ ] Documentação

**Comment by mendes-davi** [comment]
O Sensoriamento do Sistema Offgrid foi feito e é apresentado na atual seção 6.2.1 do LaTeX. Finalmente, estou produzindo os esquemáticos no KiCad para os circuitos de condicionamento dos sensores.

**Comment by josuebonfim** [comment]
O sensoriamento do gasto hídrico e dos nível de água do reservatório está me andamento. Apenas alguns parâmetros técnicos precisam ser confirmados pelo setor de Estrutura/Energia para que sejam finalizado o estudo.
