### ISSUE TITLE
Concepção do circuito de alimentação (AC -> DC)

### ISSUE THREAD

**Issue by mendes-davi** [PI2-Irri/docs#32]
**Descrição**
Tarefa voltada para concepção do circuito de alimentação (AC ->  DC) para a Central de Controle e Sistema de Atuadores.

**Tarefas**
- [x] Levantamento de especificações do circuito de alimentação.
- [x] Definição da lista de compras dos componentes.
- [x] Concepção de circuito de alimentação (Kicad)

**Critérios de Aceitação**
- [x] Documentação
- [ ] Produção do layout da PCB

**Comment by mendes-davi** [comment]
**Lista de Compras HU - Fonte de alimentação da Central de Controle**

- [LM 2576 - 5V](https://www.huinfinito.com.br/reguladores-de-tensao/769-lm2576-50.html)
- Diodo Schottky 3A 1N5822
- [CAPACITOR ELETROLITICO 100uF/50V](https://www.huinfinito.com.br/capacitor-eletrolitico/93-capacitor-eletrolitico-100uf-50v.html)
- Indutor Toroidal 100uH 3A (e.g. Pulse Eng. PE−92108)
- [CAPACITOR ELETROLITICO 1000uF/16V](https://www.huinfinito.com.br/capacitor-eletrolitico/115-capacitor-eletrolitico-1000uf-16v.html)
- [DIODO PONTE RETIFICADORA (1000V/4A)](https://www.huinfinito.com.br/diodos/855-diodo-ponte-retificadora-1000v4a.html)
- [TRANSFORMADOR ABAIXADOR (12V+12V / 3A)](https://www.huinfinito.com.br/indutores/250-transformador-abaixador-12v12v-3a.html)

**Comment by josuebonfim** [comment]
**Lista de Compras HU - Fonte de alimentação do Sistema de Atuadores**

- [1 Transistor TBJ TIP42 PNP](https://www.huinfinito.com.br/pnp/461-transistor-tip42c-pnp-plastico.html)
- 1 Resistor 270Ohms 1/2W
- 1 Resistor 1KOhms 1/2W
- [2 Capacitores 1000uF/25V Eletrolitico](https://www.huinfinito.com.br/capacitor-eletrolitico/116-capacitor-eletrolitico-1000uf-25v.html)
- [1 Capacitor 100uF/25V Eletrolitico](https://www.huinfinito.com.br/capacitor-eletrolitico/92-capacitor-eletrolitico-100uf-25v.html)
- [1 Capacitor 0.1uF/50V Cerâmico](https://www.huinfinito.com.br/capacitor-ceramico/40-capacitor-ceramico-100nf-50v.html)
- 4 diodos 1N4002 - 100V, 1A
- [1 diodo zener 1N4734A 5,6V 1W](https://www.huinfinito.com.br/diodos/210-diodo-zener-1n4734-56v-1w.html)
- [1 transformador 230VAC - 6.3VAC 1A](https://www.huinfinito.com.br/indutores/756-transformador-abaixador-6v6v-1a.html)

**Comment by mendes-davi** [comment]
As tarefas foram concluidas por: @mendes-davi  & @josuebonfim. A issue será fechada quando acabar de montar a lista de compras dos componentes
