### ISSUE TITLE
Módulos Medidores - Especificação de Sensoriamento

### ISSUE THREAD

**Issue by mendes-davi** [PI2-Irri/docs#8]
**Descrição**

Tópico destinado para realização da especificação do Sensoriamento dos Módulos Medidores por parte do time de Eletrônica.

**Tarefas**

Quanto ao sensor de umidade do solo,
- [x] Caracterização dos sensores de umidade do solo
- [x] Procedimento de calibração do sensor
- [x] Dimensionamento de IO & Alimentação (Tensão, Corrente e Potência)
- [x] Especificação de condicionamento do sinal (Analógico e/ou Digital)

Quanto ao sensor de temperatura do solo,
- [x] Caracterização dos sensores de temperatura do solo
- [x] Procedimento de calibração do sensor
- [x] Dimensionamento de IO & Alimentação (Tensão, Corrente e Potência)
- [x] Especificação de condicionamento do sinal (Analógico e/ou Digital)

Quanto ao sensoriamento do nível de carga das baterias,
- [x] Caracterização dos sensores de nível de carga
- [x] Procedimento de calibração do sensor
- [x] Dimensionamento de IO & Alimentação (Tensão, Corrente e Potência)
- [x] Especificação de condicionamento do sinal (Analógico e/ou Digital)

**Critérios de Aceitação**

- [x] Documentação do Sensoriamento
- [x] Documentação do Condicionamento dos Sinais
- [x] Documentação do Procedimento de Calibração

**Comment by josuebonfim** [comment]
1. Sensor de umidade

- [ ] Verificar o tipo de solo
- [ ] Verificar procedimento de calibração baseado no tipo de solo

2. Sensor de temperatura

- [ ] Verificar procedimento de calibração
